package com.example.customquery.entity;

public enum CategoryWork {
    VALIDATION,ASKENGINEERS,ASKQUALITY,ASKMAINTENANCE,DATOS,PRINTER,SCANNER,WINTESTEM,RACK,CARDS,COMPILE,REFERENCEWARIABLES,ETQ,OTHER
}
